### ISSUE TITLE
No credentials provided - after upgrading to version 2

### ISSUE THREAD

**Issue by eXtrem0us** [jenkinsci/zulip-plugin#40]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Jenkins: 2.412
OS: Linux - 5.4.0-153-generic
Java: 17.0.7 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
ace-editor:1.1
ansicolor:1.0.2
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:159.v25b_c67cd35fb_
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
authentication-tokens:1.53.v1c90fd9191a_b_
bootstrap4-api:4.6.0-6
bootstrap5-api:5.3.0-1
bouncycastle-api:2.28
branch-api:2.1122.v09cb_8ea_8a_724
build-timeout:1.31
build-user-vars-plugin:1.9
caffeine-api:3.1.6-115.vb_8b_b_328e59d8
checks-api:2.0.0
cloudbees-folder:6.815.v0dd5a_cb_40e0e
command-launcher:100.v2f6722292ee8
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
credentials:1254.vb_96f366e7b_a_d
credentials-binding:604.vb_64480b_c56ca_
dark-theme:336.v02165cd8c2ee
data-tables-api:1.13.4-3
display-url-api:2.3.7
docker-commons:422.v9d1a_89cede51
docker-workflow:563.vd5d2e5c4007f
durable-task:507.v050055d0cb_dd
echarts-api:5.4.0-5
email-ext:2.99
envinject:2.901.v0038b_6471582
envinject-api:1.199.v3ce31253ed13
external-monitor-job:206.v9a_94ff0b_4a_10
font-awesome-api:6.4.0-1
git:5.1.0
git-client:4.4.0
git-server:99.va_0826a_b_cdfa_d
github:1.37.1
github-api:1.314-431.v78d72a_3fe4c3
github-branch-source:1728.v859147241f49
gitlab-plugin:1.7.14
global-slack-notifier:1.5
google-oauth-plugin:1.0.9
gradle:2.8.1
handlebars:3.0.8
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:233.vdc1a_ec702cff
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:66.vd8fa_64ee91b_d
jersey2-api:2.40-1
jjwt-api:0.11.5-77.v646c772fddb_0
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.7.0-1
jsch:0.2.8-65.v052c39de79b_2
junit:1214.va_2f9db_3e6de0
kubernetes:3952.v88e3b_0cf300b_
kubernetes-cli:1.12.0
kubernetes-client-api:6.4.1-215.v2ed17097a_8e9
kubernetes-credentials:0.10.0
kubernetes-pipeline-devops-steps:1.6
ldap:682.v7b_544c9d1512
lockable-resources:1172.v4b_8fc8eed570
mailer:457.v3f72cb_e015e5
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.1.8
matrix-project:789.v57a_725b_63c79
metrics:4.2.18-439.v86a_20b_a_8318b_
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
momentjs:1.1.1
oauth-credentials:0.645.ve666a_c332668
okhttp-api:4.11.0-145.vcb_8de402ef81
pam-auth:1.10
pipeline-build-step:496.v2449a_9a_221f2
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:656.va_a_ceeb_6ffb_f7
pipeline-input-step:468.va_5db_051498a_4
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2141.v5402e818a_779
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:2.2141.v5402e818a_779
pipeline-model-extensions:2.2141.v5402e818a_779
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2141.v5402e818a_779
pipeline-stage-view:2.33
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.3.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
postbuild-task:1.9
resource-disposer:0.22
saml:4.418.vdfa_7489a_b_a_2d
scm-api:676.v886669a_199a_a_
script-security:1251.vfe552ed55f8d
simple-theme-plugin:160.vb_76454b_67900
slack:664.vc9a_90f8b_c24a_
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
sonar:2.15
ssh-credentials:305.v8f4381501156
ssh-slaves:2.877.v365f5eb_a_b_eec
sshd:3.303.vefc7119b_ec23
structs:324.va_f5d6774f3a_d
subversion:2.17.2
theme-manager:193.vcef22f6c5f2b_
timestamper:1.25
token-macro:359.vb_cde11682e0c
tool-labels-plugin:3.0
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
windows-slaves:1.8.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1219.v05cd837ea_249
workflow-basic-steps:1017.vb_45b_302f0cea_
workflow-cps:3697.vb_470e454c232
workflow-cps-global-lib:609.vd95673f149b_b
workflow-durable-task-step:1247.v7f9dfea_b_4fd0
workflow-job:1316.vd2290d3341a_f
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.45
zulip:2.0.0

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker image `jenkins/jenkins:latest-jdk17`. Here's the container base image info:
```
$ cat /etc/os-release
```
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Reproduction steps

1. having a Jenkins with the old / working Zulip plugin installed. Jenkins already has this issue #35. So, I postponed upgrading Jenkins, until the issue rectified.
2. upgrading all plugins (Zulip Plugin is not upgraded in this phase, because it is no compatible to the older Jenkins version)
3. upgrading Jenkins (`docker pull jenkins/jenkins:latest-jdk17`)
4. starting the new version of Jenkins, with old plugins.
5. upgrading all plugins (in this phase, Zulip Plugin is upgraded to version 2)

### Expected Results

Jenkins send messages by using `zulipSend message` or `zulipNotification` commands.

### Actual Results

The message isn't sent. No any exceptions are raised during pipeline execution. This is the console output of Jenkins:
```
2023-07-02 19:25:54.251+0000 [id=310]      SEVERE  jenkins.plugins.zulip.Zulip#post: Error sending Zulip message: 
java.io.IOException: No credentials provided
   at java.net.http/jdk.internal.net.http.AuthenticationFilter.response(AuthenticationFilter.java:312)
   at java.net.http/jdk.internal.net.http.MultiExchange.responseFilters(MultiExchange.java:248)
   at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$6(MultiExchange.java:413)
   at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
   at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
   at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
   at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
   at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
   at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157)
   at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
   at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
   at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
   at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
   at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.handle(Http1Response.java:695)
   at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.handle(Http1Response.java:621)
   at java.net.http/jdk.internal.net.http.Http1Response$Receiver.accept(Http1Response.java:612)
   at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.tryAsyncReceive(Http1Response.java:668)
   at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:233)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
   at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:305)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:274)
   at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.asyncReceive(Http1AsyncReceiver.java:464)
   at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onNext(Http1AsyncReceiver.java:584)
   at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onNext(Http1AsyncReceiver.java:541)
   at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210)
   at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492)
   at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295)
   at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316)
   at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
   at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232)
   at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198)
   at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:444)
   at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:268)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
   at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
Caused: java.io.IOException: No credentials provided
   at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:586)
   at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
   at jenkins.plugins.zulip.Zulip.post(Zulip.java:155)
   at jenkins.plugins.zulip.Zulip.sendStreamMessage(Zulip.java:180)
   at jenkins.plugins.zulip.ZulipSendStep.perform(ZulipSendStep.java:50)
   at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
   at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
   at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
   at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

### Anything else?

I checked out the **Zulip API Key**  in **Manage Jenkins > System > Zulip Notification Settings**.
I inspected the Concealed Password, which returns the encoded API Key... and then I decoded it. It was correct. I changed the API key again. Unfortunately, nothing changed in result.
### update
I setup a new Jenkins environment from scratch and installed Zulip Plugin in it. It worked in the new environment. However, I compared `jenkins_home/jenkins.plugins.zulip.ZulipNotifier.xml` in both environments. There were no differences, except `<api key>` tag, which were probably encoded with their own Jenkins master keys.

**Comment by butchyyyy** [comment]
@eXtrem0us Version 2 sends a basic authorization header on every request to authenticate with the Zulip APIs same as previous versions.

Any chance you have a proxy requiring authentication configured in Jenkins settings, but did not provide the credentials?

**Comment by ebonnet31** [comment]
Hi 
I just upgraded to zulip plugin version 2 and I have experienced exactly the same issue and stack trace.
My proxy settings are ok as I have been able to update properly plugins using that proxy.

I think my zulip credentials are ok.

context : 
- jenkins 2.397
- zulip plugin 2.0.0

-update
I updated to jenkins 2.417. Same issue.
Unfortunately, I can't recreate a jenkins instance from scratch as there are other people using/working on it.

**Comment by butchyyyy** [comment]
The only way I was able to reproduce the error was when I had a proxy requiring authentication configured in the Jenkins settings, but I did not provide the proxy user:

Proxy config | Proxy error
:-------------------------:|:-------------------------:
<img width="1194" alt="image" src="https://github.com/jenkinsci/zulip-plugin/assets/17402486/58592326-fbb3-4f8b-8cda-5f2cae158029"> | <img width="1156" alt="image" src="https://github.com/jenkinsci/zulip-plugin/assets/17402486/dd503e91-1f63-42bd-be29-eb2f8f1a0781">

I have released a new version 2.1.0 with more verbose logging around authentication. If you could please update to it once it hits the update centre and then:

1. Configure verbose logging for Zulip in your Jenkins instance
\
    <img width="1548" alt="image" src="https://github.com/jenkinsci/zulip-plugin/assets/17402486/872d7e00-5bd6-47b5-9e33-43e301de4e81">
1. Try to run a Jenkins job that sends or notifies to Zulip chat.
1. In an ideal scenario, you should see something like this:
\
    <img width="539" alt="image" src="https://github.com/jenkinsci/zulip-plugin/assets/17402486/841c0142-7d2b-43b6-ad89-62a513ae0d19">
\
    Since this is not working for you you'll see something else, please post this something else here. Thanks!

**Comment by ebonnet31** [comment]
Hi @butchyyyy 
I set up the logs and I had the following messages :
![image](https://github.com/jenkinsci/zulip-plugin/assets/3205426/7f959897-8a5d-4a18-b1e8-6c4b87437ba3)

Our zulip is on the intranet and is an exception in the jenkins proxy host list.

**Comment by butchyyyy** [comment]
Thanks for providing the logs @ebonnet31! In your case, the proxy is not involved due to no proxy host exclusion. Instead, it's the Zulip server returning 401/requesting authentication. The plugin does include credentials (basic authorization) on each Zulip API request so it means the credentials were not valid/rejected by the server.

I can reproduce this locally by entering the wrong credentials into my Jenkins instance:

![image](https://github.com/jenkinsci/zulip-plugin/assets/17402486/2ed94af9-b8b1-415d-9cad-fb3c886fc942)

Can you please double-check your global Jenkins configuration and verify that the `Zulip User Email` and `Zulip API Key` are correct / for the enabled Zulip bot?

I'll look into adjusting the error handling so it's more obvious what the problem is.

**Comment by ebonnet31** [comment]
Hi @butchyyyy 
I have tried to reset the mail + api key. 

To be sure of the parameters, I tried the parameters using a curl from the zulip example 

```
# For stream messages
curl -X POST https://yourZulipDomain.zulipchat.com/api/v1/messages \
    -u BOT_EMAIL_ADDRESS:BOT_API_KEY \
    --data-urlencode type=stream \
    --data-urlencode 'to="Denmark"' \
    --data-urlencode topic=Castle \
    --data-urlencode 'content=I come not, friends, to steal away your hearts.'
```

The curl works with the same apiKey/mail set in jenkins zulip system properties. 
But I still have the same jenkins/zulip error.

**Comment by ebonnet31** [comment]
maybe an additional suggestion :  provide a "test" button in the jenkins system configuration to check that the parameters are ok.

**Comment by ebonnet31** [comment]
Additional info : at one point, I entered a wrong url (http instead of https) to see the changes. I had a 301. However, I could see in the log the message :
```
We sent:api-key=XXXX&subject=AAAA&to=TTTT&type=stream&email=toto%40toto.com&content=Started+build+%2318+of+project+test-zulip
```
XXX/AAA/TTT/email being correct.

-> seems to show parameters are ok. 

I entered back the right url  => same exception message.

**Comment by butchyyyy** [comment]
@ebonnet31  Thanks for verifying the credentials are correct and for providing all of the additional info. It looks like encoding the credentials into the basic authorization header does not work as expected in your case.

https://github.com/jenkinsci/zulip-plugin/blob/master/src/main/java/jenkins/plugins/zulip/Zulip.java#L146-L147

I have tried a bunch of things but had no luck reproducing 😞

Any idea on what could be different in your environment? e.g.:
- Special characters in the bot name / access key
- Charset the Jenkins JVM runs with
- ...

**Comment by ebonnet31** [comment]
Hi @butchyyyy 
jenkins run on windows with a default charset CP-1252.  I have no idea for the the zulip server.
I noticed the line : 
https://github.com/jenkinsci/zulip-plugin/blob/a5e908a8e9609e07f9b88a6f98a314027b10de7b/src/main/java/jenkins/plugins/zulip/Zulip.java#L34

As a trial what do you suggest ? I can try to change my jenkins options to have a UTF8 charset for the VM. I'll be able to try that tomorrow.

**Comment by JeffLi01** [comment]
I run into the exact problem.
I tried to reform the Zulip class to a standlone one (by removing dependencies for jenkins) to run with Java on local command line, and got the same error. But with a different approach I succeeded to send  message to zulip server.

1. First I tried this:

`java.exe .\Zulip.java`

```java
// Zulip.java
import java.io.IOException;
import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpHeaders;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

/**
 * Sends message to Zulip stream
 */
public class Zulip {

    private static final Charset encodingCharset = StandardCharsets.UTF_8;

    private String url;
    private String email;
    private String apiKey;
    private static Logger LOGGER = Logger.getLogger("");

    public Zulip(String url, String email, String apiKey) {
        super();
        if (url != null && url.length() > 0 && !url.endsWith("/")) {
            url = url + "/";
        }
        this.url = url;
        this.email = email;
        this.apiKey = apiKey;
    }

    protected void configureAuthenticator(HttpClient.Builder httpClientBuilder) {
        httpClientBuilder.authenticator(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                LOGGER.log(Level.FINE, "{0} authentication requested from {1}:{2}", new Object[] { getRequestorType(),
                        getRequestingHost(), getRequestingPort() });

                switch (getRequestorType()) {
                    default:
                        LOGGER.log(Level.FINE, "Unsupported authentication request");

                        return null;
                }
            }
        });
    }

    protected HttpClient getClient() throws MalformedURLException {
        HttpClient.Builder httpClientBuilder = HttpClient.newBuilder();
        configureAuthenticator(httpClientBuilder);
        return httpClientBuilder.build();
    }

    protected URI getApiEndpoint(String method) {
        StringBuilder uri = new StringBuilder();

        if (this.url.length() > 0) {
            uri.append(this.url);
            uri.append("api/v1/");
        } else {
            uri.append("https://api.zulip.com/v1/");
        }

        uri.append(method);

        return URI.create(uri.toString());
    }

    public String getApiKey() {
        return this.apiKey;
    }

    public String getEmail() {
        return this.email;
    }

    public HttpResponse<String> post(String method, Map<String, String> parameters) {
        try {
            String body = parameters.entrySet()
                    .stream()
                    .map(e -> encodeValue(e))
                    .collect(Collectors.joining("&"));
            System.out.println(body);

            String auth_info = this.getEmail() + ":" + this.getApiKey();
            String encoded_auth = Base64.getEncoder().encodeToString(auth_info.getBytes(encodingCharset));

            HttpRequest httpRequest = HttpRequest.newBuilder()
                    .uri(getApiEndpoint(method))
                    .header("User-Agent", "ZulipJenkins/0.1.2")
                    .header("Content-Type", "application/x-www-form-urlencoded")
                    .header("Authorization", "Basic " + encoded_auth)
                    .POST(HttpRequest.BodyPublishers.ofString(body, encodingCharset))
                    .build();

            HttpClient client = getClient();

            HttpResponse<String> httpResponse = client.send(httpRequest, HttpResponse.BodyHandlers.ofString());

            if (httpResponse.statusCode() != 200) {
                LOGGER.log(Level.SEVERE,
                        "Error sending Zulip message:\nStatus:" + httpResponse.statusCode() + "\nBody:"
                                + httpResponse.body() + "\n\n" +
                                "We sent:" + body);
            }

            return httpResponse;
        } catch (IOException | InterruptedException e) {
            LOGGER.log(Level.SEVERE, "Error sending Zulip message: ", e);
        }

        return null;
    }

    public HttpResponse<String> sendStreamMessage(String stream, String subject, String message) {
        Map<String, String> parameters = new HashMap<String, String>();

        parameters.put("api-key", this.getApiKey());
        parameters.put("email", this.getEmail());
        parameters.put("type", "stream");
        parameters.put("to", stream);
        parameters.put("subject", subject);
        parameters.put("content", message);

        return post("messages", parameters);
    }

    private String encodeValue(Map.Entry<String, String> value) {
        String toEncode = value.getValue() != null ? value.getValue() : "";
        String encodedValue = URLEncoder.encode(toEncode, encodingCharset);

        return value.getKey() + "=" + encodedValue;
    }

    public static void main(String[] args) {
        LOGGER.setLevel(Level.SEVERE);

        String token = "EEfIvlMKhrWHLCK4UTRNM1U7lUlxnxw5";
        Zulip zulip = new Zulip("https://zulip.fw.trd", "jenkins-bot@zulip.fw.trd", token);
        zulip.sendStreamMessage("jenkins", "subject", "message");
    }
}
```

2. Second, I tried this and succeeded. I can't tell the difference between the two method due to I am not familar with Java. Maybe you can find it out and solve the problem.

`java .\ZulipBotMessageSender.java`
```java
// ZulipBotMessageSender.java
import java.io.IOException;
import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

/**
 * Sends message to Zulip stream
 */
public class Zulip {

    private static final Charset encodingCharset = StandardCharsets.UTF_8;

    private String url;
    private String email;
    private String apiKey;
    private static Logger LOGGER = Logger.getLogger("");

    public Zulip(String url, String email, String apiKey) {
        super();
        if (url != null && url.length() > 0 && !url.endsWith("/")) {
            url = url + "/";
        }
        this.url = url;
        this.email = email;
        this.apiKey = apiKey;
    }

    protected void configureAuthenticator(HttpClient.Builder httpClientBuilder) {
        httpClientBuilder.authenticator(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                LOGGER.log(Level.FINE, "{0} authentication requested from {1}:{2}", new Object[] { getRequestorType(),
                        getRequestingHost(), getRequestingPort() });

                switch (getRequestorType()) {
                    default:
                        LOGGER.log(Level.FINE, "Unsupported authentication request");

                        return null;
                }
            }
        });
    }

    protected HttpClient getClient() throws MalformedURLException {
        HttpClient.Builder httpClientBuilder = HttpClient.newBuilder();
        configureAuthenticator(httpClientBuilder);
        return httpClientBuilder.build();
    }

    protected URI getApiEndpoint(String method) {
        StringBuilder uri = new StringBuilder();

        if (this.url.length() > 0) {
            uri.append(this.url);
            uri.append("api/v1/");
        } else {
            uri.append("https://api.zulip.com/v1/");
        }

        uri.append(method);

        return URI.create(uri.toString());
    }

    public String getApiKey() {
        return this.apiKey;
    }

    public String getEmail() {
        return this.email;
    }

    public HttpResponse<String> post(String method, Map<String, String> parameters) {
        try {
            String body = parameters.entrySet()
                    .stream()
                    .map(e -> encodeValue(e))
                    .collect(Collectors.joining("&"));
            System.out.println(body);

            String auth_info = this.getEmail() + ":" + this.getApiKey();
            String encoded_auth = Base64.getEncoder().encodeToString(auth_info.getBytes(encodingCharset));

            HttpRequest httpRequest = HttpRequest.newBuilder()
                    .uri(getApiEndpoint(method))
                    .header("User-Agent", "ZulipJenkins/0.1.2")
                    .header("Content-Type", "application/x-www-form-urlencoded")
                    .header("Authorization", "Basic " + encoded_auth)
                    .POST(HttpRequest.BodyPublishers.ofString(body, encodingCharset))
                    .build();

            HttpClient client = getClient();

            HttpResponse<String> httpResponse = client.send(httpRequest, HttpResponse.BodyHandlers.ofString());

            if (httpResponse.statusCode() != 200) {
                LOGGER.log(Level.SEVERE,
                        "Error sending Zulip message:\nStatus:" + httpResponse.statusCode() + "\nBody:"
                                + httpResponse.body() + "\n\n" +
                                "We sent:" + body);
            }

            return httpResponse;
        } catch (IOException | InterruptedException e) {
            LOGGER.log(Level.SEVERE, "Error sending Zulip message: ", e);
        }

        return null;
    }

    public HttpResponse<String> sendStreamMessage(String stream, String subject, String message) {
        Map<String, String> parameters = new HashMap<String, String>();

        parameters.put("api-key", this.getApiKey());
        parameters.put("email", this.getEmail());
        parameters.put("type", "stream");
        parameters.put("to", stream);
        parameters.put("subject", subject);
        parameters.put("content", message);

        return post("messages", parameters);
    }

    private String encodeValue(Map.Entry<String, String> value) {
        String toEncode = value.getValue() != null ? value.getValue() : "";
        String encodedValue = URLEncoder.encode(toEncode, encodingCharset);

        return value.getKey() + "=" + encodedValue;
    }

    public static void main(String[] args) {
        LOGGER.setLevel(Level.SEVERE);

        String token = "EEfIvlMKhrWHLCK4UTRNM1U7lUlxnxw5";
        Zulip zulip = new Zulip("https://zulip.fw.trd", "jenkins-bot@zulip.fw.trd", token);
        zulip.sendStreamMessage("jenkins", "subject", "message");
    }
}
```

**Comment by JeffLi01** [comment]
I finally found out that the problem had something to do with below line:

`configureAuthenticator(httpClientBuilder);`

When I commented this line out, then the message got sent. Maybe current implemention is not suitable for deployment of Jenkins without proxy.

**Comment by butchyyyy** [comment]
> As a trial what do you suggest ? I can try to change my jenkins options to have a UTF8 charset for the VM. I'll be able to try that tomorrow.

That would be great. My test Jenkins instance runs with `UTF-8` so I'll try to run it with `CP-1252` and see if I can repro (won't manage before tomorrow as well).

**Comment by butchyyyy** [comment]
> I finally found out that the problem had something to do with below line:
> 
> `configureAuthenticator(httpClientBuilder);`
> 
> When I commented this line out, then the message got sent. Maybe current implemention is not suitable for deployment of Jenkins without proxy.

The authenticator should only be invoked when the server requests authentication (401 from Zulip server or 407 from proxy). My expectation would be that with authenticator removed, it will not fail with `java.io.IOException: No credentials provided`, but the message will still fail to send.

Removing the authenticator and sending the `Proxy-Authorization` header preemptively (if configured in Jenkins) is an option, but I'd like to get to the bottom of the problem before making changes like this.

**Comment by JeffLi01** [comment]
I checked return status code from Zulip with curl but found none except `200`.

```bash
curl -X POST https://zulip.fw.trd/api/v1/messages -u jenkins-bot@zulip.fw.trd:EEfIvlMKhrWHLCK4UTRNM1U7lUlxnxw5 --data-urlencode type=stream --data-urlencode 'to=jenkins' --data-urlencode topic=OpenBMC --data-urlencode 'content=OpenBMC Build #199 SUCCEED!' -H "User-Agent: ZulipJenkins/0.1.2" -iv
```

Then I add a 
`System.out.println("in getPasswordAuthentication");`
in method `getPasswordAuthentication()` and the message got printed. So below assumption was not true.

> The authenticator should only be invoked when the server requests authentication (401 from Zulip server or 407 from proxy).

**Comment by JeffLi01** [comment]
I think you may intend to register a DEFAULT Authendicator instead of register a ALWAYS used one.

I tried this code, it works on non-proxy configuration.
```java
    protected void configureAuthenticator(HttpClient.Builder httpClientBuilder) {
        Authenticator.setDefault(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                System.out.println("in getPasswordAuthentication");
                LOGGER.log(Level.FINE, "{0} authentication requested from {1}:{2}", new Object[] { getRequestorType(),
                        getRequestingHost(), getRequestingPort() });

                switch (getRequestorType()) {
                    default:
                        LOGGER.log(Level.FINE, "Unsupported authentication request");

                        return null;
                }
            }
        });
    }
```

**Comment by JeffLi01** [comment]
I wonder if the root cause is mixing two authentication methods: header based and Authenticator based. The Authenticator is used but SERVER type is not handled. The header based authentication is ignored.

The code below works.
```java
    protected void configureAuthenticator(HttpClient.Builder httpClientBuilder) {
        httpClientBuilder.authenticator(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                System.out.println("in getPasswordAuthentication");
                LOGGER.log(Level.FINE, "{0} authentication requested from {1}:{2}", new Object[] { getRequestorType(),
                        getRequestingHost(), getRequestingPort() });

                switch (getRequestorType()) {
                    // case PROXY:
                    //     ProxyConfiguration proxyConfiguration = Jenkins.get().proxy;

                    //     if (ZulipUtil.isValueSet(proxyConfiguration.getUserName())) {
                    //         LOGGER.log(Level.FINE, "Using proxy authentication username: {0}, password: ******",
                    //                 proxyConfiguration.getUserName());
                    //         return new PasswordAuthentication(proxyConfiguration.getUserName(),
                    //                 Secret.toString(proxyConfiguration.getSecretPassword()).toCharArray());
                    //     }

                    //     LOGGER.log(Level.FINE, "Proxy authentication not configured in Jenkins");

                    //     return null;
                    case SERVER:
                        LOGGER.log(Level.FINE, "SERVER authentication:");

                        return new PasswordAuthentication(email, apiKey.toCharArray());
                    default:
                        LOGGER.log(Level.FINE, "Unsupported authentication request");

                        return null;
                }
            }
        });
    }
```

**Comment by ebonnet31** [comment]
Hi @butchyyyy 
I have tried  the UTF-8 encoding

```
set JENKINS_OPTS=-Dfile.encoding=UTF-8 -Djdk.http.auth.tunneling.disabledSchemes=""
```
Reset the parameters, so that file would be saved.
upgraded jenkins to the last version and updated plugins.
I still have the same error.

**Comment by butchyyyy** [comment]
So... I'm mostly testing locally with Java 11 to make sure the plugin works with the minimal required Java version. I have now switched to Java 17 and I can reproduce the issue there...

I always considered Java to be good in backwards compatibility so I'm flabbergasted this is behaving differently in between versions 😞 

The original idea of directly setting the header was to avoid an extra round-trip to the Zulip server, but since this is behaving inconsistently between Java versions, I'm gonna leave the auth headers in the sole discretion of the `Authenticator`.

I'll release 2.1.1 version today with a fix.

**Comment by ebonnet31** [comment]
I didn't had suspicion on the JDK, but yes I am on the JDK 17 too.

**Comment by butchyyyy** [comment]
This is now released in version [2.1.1](https://github.com/jenkinsci/zulip-plugin/releases/tag/2.1.1). Please note that it can take up to 24 hours for the new version to show in Jenkins update centre.

**Comment by ebonnet31** [comment]
Just tried it. It works. All good now.
Thanks a lot !

**Comment by eXtrem0us** [comment]
Finally it works!
Thank you @butchyyyy !
